# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [8]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 4. How many products cost more than $10.00?

In [9]:
# change the item_price to numeric values
chipo['item_price'] = chipo.apply(lambda x: float(x['item_price'].replace('$', '')), axis = 1)
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,NaN,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25

In [11]:
chipo.loc[chipo.item_price > 10.00]['item_name'].nunique()

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [15]:
# unique combinations
chipo.loc[chipo.item_price > 10.00][['item_name', 'item_price']].drop_duplicates().reset_index(drop=True)

                       item_name  item_price
0                   Chicken Bowl       16.98
1                   Chicken Bowl       10.98
2                  Steak Burrito       11.75
3                   Chicken Bowl       11.25
4                Chicken Burrito       10.98
5                  Barbacoa Bowl       11.75
6                 Veggie Burrito       11.25
7                    Veggie Bowl       11.25
8             Chicken Soft Tacos       11.25
9                     Steak Bowl       11.75
10              Carnitas Burrito       11.75
11                 Carnitas Bowl       11.75
12              Barbacoa Burrito       11.75
13            Chicken Salad Bowl       22.50
14                 Steak Burrito       11.48
15                 Steak Burrito       17.98
16               Chicken Burrito       17.50
17                  Chicken Bowl       17.50
18                 Carnitas Bowl       11.48
19               Chicken Burrito       11.25
20         Barbacoa Crispy Tacos       11.75
21             Veggie Salad Bowl       11.25
22                    Steak Bowl       11.48
23          Chicken Crispy Tacos       17.50
24                 Chicken Salad       10.98
25              Steak Salad Bowl       23.78
26            Chicken Salad Bowl       17.50
27                 Steak Burrito       11.08
28                 Steak Burrito       22.16
29            Chicken Soft Tacos       17.50
..                           ...         ...
67         Barbacoa Crispy Tacos       18.50
68           Carnitas Soft Tacos       11.75
69            Steak Crispy Tacos       11.75
70              Carnitas Burrito       18.50
71           Chips and Guacamole       13.35
72            Steak Crispy Tacos       17.98
73              Carnitas Burrito       11.08
74                  Chicken Bowl       10.58
75                 Steak Burrito       22.96
76           Barbacoa Soft Tacos       11.48
77              Barbacoa Burrito       11.48
78                    Steak Bowl       26.07
79                    Steak Bowl       18.50
80               Chicken Burrito       16.98
81             6 Pack Soft Drink       12.98
82                 Carnitas Bowl       35.25
83  Chips and Fresh Tomato Salsa       44.25
84                 Bottled Water       10.50
85                Veggie Burrito       33.75
86               Chicken Burrito       26.25
87            Chicken Soft Tacos       21.96
88               Chicken Burrito       16.38
89                 Side of Chips       13.52
90             Veggie Soft Tacos       16.98
91         Carnitas Crispy Tacos       17.98
92          Chicken Crispy Tacos       16.98
93                 Bottled Water       15.00
94              Steak Soft Tacos       18.50
95           Chips and Guacamole       17.80
96                 Barbacoa Bowl       11.49

[97 rows x 2 columns]

### Step 6. Sort by the name of the item

In [18]:
chipo.loc[chipo.item_price > 10.00][['item_name', 'item_price']].drop_duplicates().sort_values(['item_name']).reset_index(drop=True)

                item_name  item_price
0       6 Pack Soft Drink       12.98
1           Barbacoa Bowl       11.49
2           Barbacoa Bowl       11.48
3           Barbacoa Bowl       11.75
4        Barbacoa Burrito       11.08
5        Barbacoa Burrito       11.48
6        Barbacoa Burrito       11.75
7   Barbacoa Crispy Tacos       11.48
8   Barbacoa Crispy Tacos       11.75
9   Barbacoa Crispy Tacos       18.50
10    Barbacoa Salad Bowl       11.89
11    Barbacoa Soft Tacos       11.75
12    Barbacoa Soft Tacos       11.48
13          Bottled Water       15.00
14          Bottled Water       10.50
15                   Bowl       22.20
16          Carnitas Bowl       11.75
17          Carnitas Bowl       35.25
18          Carnitas Bowl       11.48
19          Carnitas Bowl       11.08
20          Carnitas Bowl       23.50
21       Carnitas Burrito       18.50
22       Carnitas Burrito       11.08
23       Carnitas Burrito       11.48
24       Carnitas Burrito       11.75
25  Carnitas Crispy Tacos       17.98
26  Carnitas Crispy Tacos       11.75
27    Carnitas Salad Bowl       11.89
28    Carnitas Soft Tacos       11.75
29           Chicken Bowl       16.98
..                    ...         ...
67             Steak Bowl       26.07
68             Steak Bowl       11.08
69             Steak Bowl       11.48
70             Steak Bowl       17.98
71             Steak Bowl       11.75
72          Steak Burrito       22.96
73          Steak Burrito       11.75
74          Steak Burrito       11.08
75          Steak Burrito       17.98
76          Steak Burrito       11.48
77          Steak Burrito       22.16
78          Steak Burrito       18.50
79          Steak Burrito       23.50
80          Steak Burrito       27.75
81     Steak Crispy Tacos       17.98
82     Steak Crispy Tacos       11.75
83       Steak Salad Bowl       11.89
84       Steak Salad Bowl       23.78
85       Steak Soft Tacos       11.48
86       Steak Soft Tacos       18.50
87       Steak Soft Tacos       11.75
88            Veggie Bowl       16.98
89            Veggie Bowl       10.98
90            Veggie Bowl       11.25
91         Veggie Burrito       11.25
92         Veggie Burrito       10.98
93         Veggie Burrito       33.75
94      Veggie Salad Bowl       11.25
95      Veggie Soft Tacos       11.25
96      Veggie Soft Tacos       16.98

[97 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered?

In [21]:
chipo.iloc[chipo['item_price'].idxmax()]['quantity']

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [25]:
chipo.loc[chipo.item_name == 'Veggie Salad Bowl']['order_id'].nunique()

18

### Step 9. How many times did someone order more than one Canned Soda?

In [29]:
chipo.loc[(chipo.item_name == 'Canned Soda') & (chipo.quantity > 1)]['order_id'].nunique()

18